#FROM        centos:7
#RUN         yum install epel-release -y
#RUN         yum install nginx -y
#ENTRYPOINT  ["nginx", "-g", "daemon off;"]

FROM            centos:7
ENTRYPOINT      ["ping", "-c5"]
CMD             ["google.com"]
