apiVersion: v1
kind: Pod
metadata:
  name: sample6
spec:
  containers:
    - name: centos
      image: centos:7
      command:
        - sleep
        - "1000000"
      resources:
        requests:
          cpu: "500m"
          memory: "500Mi"
        limits:
          cpu: "750m"
          memory: "750Mi"
## 1CPU - 1000m core
