apiVersion: v1
kind: Pod
metadata:
  name: sample6
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: "500m"
          memory: "500Mi"
## 1CPU - 1000m core
