apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
spec:
  storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: sample7
spec:
  volumes:
    - name: test
      persistentVolumeClaim:
        claimName: test
  containers:
    - name: centos
      image: centos:7
      command:
        - sleep
        - "1000000"
      volumeMounts:
        - mountPath: "/mnt"
          name: test

